# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{roles_mongo_mapper}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kristian Mandrup}]
  s.date = %q{2011-08-17}
  s.description = %q{Makes it easy to set a role strategy on your User model in MongoMapper}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/generators/mongo_mapper/roles/core_ext.rb",
    "lib/generators/mongo_mapper/roles/roles_generator.rb",
    "lib/generators/mongo_mapper/roles/templates/role.rb",
    "lib/roles_mongo_mapper.rb",
    "lib/roles_mongo_mapper/base.rb",
    "lib/roles_mongo_mapper/embedded_role.rb",
    "lib/roles_mongo_mapper/namespaces.rb",
    "lib/roles_mongo_mapper/role.rb",
    "lib/roles_mongo_mapper/role_class.rb",
    "lib/roles_mongo_mapper/strategy.rb",
    "lib/roles_mongo_mapper/strategy/multi.rb",
    "lib/roles_mongo_mapper/strategy/multi/embed_many_roles.rb",
    "lib/roles_mongo_mapper/strategy/multi/many_roles.rb",
    "lib/roles_mongo_mapper/strategy/multi/role_strings.rb",
    "lib/roles_mongo_mapper/strategy/multi/roles_mask.rb",
    "lib/roles_mongo_mapper/strategy/shared.rb",
    "lib/roles_mongo_mapper/strategy/single.rb",
    "lib/roles_mongo_mapper/strategy/single/admin_flag.rb",
    "lib/roles_mongo_mapper/strategy/single/embed_one_role.rb",
    "lib/roles_mongo_mapper/strategy/single/one_role.rb",
    "lib/roles_mongo_mapper/strategy/single/role_string.rb",
    "roles_mongo_mapper.gemspec",
    "sandbox/test.rb",
    "spec/generator_spec_helper.rb",
    "spec/roles_mongo_mapper/generators/roles_generator_spec.rb",
    "spec/roles_mongo_mapper/strategy/api_examples.rb",
    "spec/roles_mongo_mapper/strategy/hooks.rb",
    "spec/roles_mongo_mapper/strategy/multi/embed_many_roles_spec.rb",
    "spec/roles_mongo_mapper/strategy/multi/many_roles_spec.rb",
    "spec/roles_mongo_mapper/strategy/multi/role_strings_spec.rb",
    "spec/roles_mongo_mapper/strategy/multi/roles_mask_spec.rb",
    "spec/roles_mongo_mapper/strategy/single/admin_flag_spec.rb",
    "spec/roles_mongo_mapper/strategy/single/embed_one_role_spec.rb",
    "spec/roles_mongo_mapper/strategy/single/one_role_spec.rb",
    "spec/roles_mongo_mapper/strategy/single/role_string_spec.rb",
    "spec/roles_mongo_mapper/strategy/user_setup.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/roles_mongo_mapper}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Implementation of Roles generic API for MongoMapper}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.8.5"])
      s.add_runtime_dependency(%q<bson>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<roles_generic>, [">= 0.5.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<generator-spec>, [">= 0.7.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<mongo_mapper>, [">= 0.8.5"])
      s.add_dependency(%q<bson>, [">= 1.2.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.1"])
      s.add_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_dependency(%q<sugar-high>, [">= 0.5.0"])
      s.add_dependency(%q<roles_generic>, [">= 0.5.0"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<generator-spec>, [">= 0.7.5"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<bundler>, [">= 1.0.10"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongo_mapper>, [">= 0.8.5"])
    s.add_dependency(%q<bson>, [">= 1.2.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.1"])
    s.add_dependency(%q<require_all>, ["~> 1.2.0"])
    s.add_dependency(%q<sugar-high>, [">= 0.5.0"])
    s.add_dependency(%q<roles_generic>, [">= 0.5.0"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<generator-spec>, [">= 0.7.5"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<bundler>, [">= 1.0.10"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

