require 'roles_generic'
require 'require_all'    
require 'set'
require 'sugar-high/array'
require 'mongo_mapper'
require 'roles_mongo_mapper/namespaces'
require 'roles_mongo_mapper/base'
require 'roles_mongo_mapper/strategy'
